/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gym Tracker API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  WorkoutExerciseCreate
} from '../model';

import { customAxiosInstance } from '../../lib/axios-instance';




/**
 * @summary Add Exercise To Workout
 */
export const addExerciseToWorkoutApiWorkoutExercisesPost = (
    workoutExerciseCreate: WorkoutExerciseCreate,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<unknown>(
      {url: `/api/workout-exercises`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: workoutExerciseCreate, signal
    },
      );
    }
  


export const getAddExerciseToWorkoutApiWorkoutExercisesPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addExerciseToWorkoutApiWorkoutExercisesPost>>, TError,{data: WorkoutExerciseCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof addExerciseToWorkoutApiWorkoutExercisesPost>>, TError,{data: WorkoutExerciseCreate}, TContext> => {

const mutationKey = ['addExerciseToWorkoutApiWorkoutExercisesPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addExerciseToWorkoutApiWorkoutExercisesPost>>, {data: WorkoutExerciseCreate}> = (props) => {
          const {data} = props ?? {};

          return  addExerciseToWorkoutApiWorkoutExercisesPost(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AddExerciseToWorkoutApiWorkoutExercisesPostMutationResult = NonNullable<Awaited<ReturnType<typeof addExerciseToWorkoutApiWorkoutExercisesPost>>>
    export type AddExerciseToWorkoutApiWorkoutExercisesPostMutationBody = WorkoutExerciseCreate
    export type AddExerciseToWorkoutApiWorkoutExercisesPostMutationError = HTTPValidationError

    /**
 * @summary Add Exercise To Workout
 */
export const useAddExerciseToWorkoutApiWorkoutExercisesPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addExerciseToWorkoutApiWorkoutExercisesPost>>, TError,{data: WorkoutExerciseCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addExerciseToWorkoutApiWorkoutExercisesPost>>,
        TError,
        {data: WorkoutExerciseCreate},
        TContext
      > => {
      return useMutation(getAddExerciseToWorkoutApiWorkoutExercisesPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Remove Exercise From Workout
 */
export const removeExerciseFromWorkoutApiWorkoutExercisesWorkoutExerciseIdDelete = (
    workoutExerciseId: number,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<void>(
      {url: `/api/workout-exercises/${workoutExerciseId}`, method: 'DELETE', signal
    },
      );
    }
  


export const getRemoveExerciseFromWorkoutApiWorkoutExercisesWorkoutExerciseIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeExerciseFromWorkoutApiWorkoutExercisesWorkoutExerciseIdDelete>>, TError,{workoutExerciseId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof removeExerciseFromWorkoutApiWorkoutExercisesWorkoutExerciseIdDelete>>, TError,{workoutExerciseId: number}, TContext> => {

const mutationKey = ['removeExerciseFromWorkoutApiWorkoutExercisesWorkoutExerciseIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeExerciseFromWorkoutApiWorkoutExercisesWorkoutExerciseIdDelete>>, {workoutExerciseId: number}> = (props) => {
          const {workoutExerciseId} = props ?? {};

          return  removeExerciseFromWorkoutApiWorkoutExercisesWorkoutExerciseIdDelete(workoutExerciseId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveExerciseFromWorkoutApiWorkoutExercisesWorkoutExerciseIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof removeExerciseFromWorkoutApiWorkoutExercisesWorkoutExerciseIdDelete>>>
    
    export type RemoveExerciseFromWorkoutApiWorkoutExercisesWorkoutExerciseIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Remove Exercise From Workout
 */
export const useRemoveExerciseFromWorkoutApiWorkoutExercisesWorkoutExerciseIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeExerciseFromWorkoutApiWorkoutExercisesWorkoutExerciseIdDelete>>, TError,{workoutExerciseId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeExerciseFromWorkoutApiWorkoutExercisesWorkoutExerciseIdDelete>>,
        TError,
        {workoutExerciseId: number},
        TContext
      > => {
      return useMutation(getRemoveExerciseFromWorkoutApiWorkoutExercisesWorkoutExerciseIdDeleteMutationOptions(options), queryClient);
    }
    