/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gym Tracker API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetCalendarApiWorkoutsCalendarGetParams,
  HTTPValidationError,
  ListWorkoutsApiWorkoutsGetParams,
  ListWorkoutsInRangeApiWorkoutsRangeGetParams,
  WorkoutCreate
} from '../model';

import { customAxiosInstance } from '../../lib/axios-instance';




/**
 * @summary List Workouts
 */
export const listWorkoutsApiWorkoutsGet = (
    params?: ListWorkoutsApiWorkoutsGetParams,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<unknown>(
      {url: `/api/workouts`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListWorkoutsApiWorkoutsGetQueryKey = (params?: ListWorkoutsApiWorkoutsGetParams,) => {
    return [
    `/api/workouts`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListWorkoutsApiWorkoutsGetQueryOptions = <TData = Awaited<ReturnType<typeof listWorkoutsApiWorkoutsGet>>, TError = HTTPValidationError>(params?: ListWorkoutsApiWorkoutsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWorkoutsApiWorkoutsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListWorkoutsApiWorkoutsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listWorkoutsApiWorkoutsGet>>> = ({ signal }) => listWorkoutsApiWorkoutsGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listWorkoutsApiWorkoutsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListWorkoutsApiWorkoutsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listWorkoutsApiWorkoutsGet>>>
export type ListWorkoutsApiWorkoutsGetQueryError = HTTPValidationError


export function useListWorkoutsApiWorkoutsGet<TData = Awaited<ReturnType<typeof listWorkoutsApiWorkoutsGet>>, TError = HTTPValidationError>(
 params: undefined |  ListWorkoutsApiWorkoutsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWorkoutsApiWorkoutsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listWorkoutsApiWorkoutsGet>>,
          TError,
          Awaited<ReturnType<typeof listWorkoutsApiWorkoutsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListWorkoutsApiWorkoutsGet<TData = Awaited<ReturnType<typeof listWorkoutsApiWorkoutsGet>>, TError = HTTPValidationError>(
 params?: ListWorkoutsApiWorkoutsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWorkoutsApiWorkoutsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listWorkoutsApiWorkoutsGet>>,
          TError,
          Awaited<ReturnType<typeof listWorkoutsApiWorkoutsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListWorkoutsApiWorkoutsGet<TData = Awaited<ReturnType<typeof listWorkoutsApiWorkoutsGet>>, TError = HTTPValidationError>(
 params?: ListWorkoutsApiWorkoutsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWorkoutsApiWorkoutsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Workouts
 */

export function useListWorkoutsApiWorkoutsGet<TData = Awaited<ReturnType<typeof listWorkoutsApiWorkoutsGet>>, TError = HTTPValidationError>(
 params?: ListWorkoutsApiWorkoutsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWorkoutsApiWorkoutsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListWorkoutsApiWorkoutsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create Workout
 */
export const createWorkoutApiWorkoutsPost = (
    workoutCreate: WorkoutCreate,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<unknown>(
      {url: `/api/workouts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: workoutCreate, signal
    },
      );
    }
  


export const getCreateWorkoutApiWorkoutsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWorkoutApiWorkoutsPost>>, TError,{data: WorkoutCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createWorkoutApiWorkoutsPost>>, TError,{data: WorkoutCreate}, TContext> => {

const mutationKey = ['createWorkoutApiWorkoutsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createWorkoutApiWorkoutsPost>>, {data: WorkoutCreate}> = (props) => {
          const {data} = props ?? {};

          return  createWorkoutApiWorkoutsPost(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateWorkoutApiWorkoutsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createWorkoutApiWorkoutsPost>>>
    export type CreateWorkoutApiWorkoutsPostMutationBody = WorkoutCreate
    export type CreateWorkoutApiWorkoutsPostMutationError = HTTPValidationError

    /**
 * @summary Create Workout
 */
export const useCreateWorkoutApiWorkoutsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWorkoutApiWorkoutsPost>>, TError,{data: WorkoutCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createWorkoutApiWorkoutsPost>>,
        TError,
        {data: WorkoutCreate},
        TContext
      > => {
      return useMutation(getCreateWorkoutApiWorkoutsPostMutationOptions(options), queryClient);
    }
    /**
 * @summary List Workouts In Range
 */
export const listWorkoutsInRangeApiWorkoutsRangeGet = (
    params: ListWorkoutsInRangeApiWorkoutsRangeGetParams,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<unknown>(
      {url: `/api/workouts/range`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListWorkoutsInRangeApiWorkoutsRangeGetQueryKey = (params?: ListWorkoutsInRangeApiWorkoutsRangeGetParams,) => {
    return [
    `/api/workouts/range`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListWorkoutsInRangeApiWorkoutsRangeGetQueryOptions = <TData = Awaited<ReturnType<typeof listWorkoutsInRangeApiWorkoutsRangeGet>>, TError = HTTPValidationError>(params: ListWorkoutsInRangeApiWorkoutsRangeGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWorkoutsInRangeApiWorkoutsRangeGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListWorkoutsInRangeApiWorkoutsRangeGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listWorkoutsInRangeApiWorkoutsRangeGet>>> = ({ signal }) => listWorkoutsInRangeApiWorkoutsRangeGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listWorkoutsInRangeApiWorkoutsRangeGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListWorkoutsInRangeApiWorkoutsRangeGetQueryResult = NonNullable<Awaited<ReturnType<typeof listWorkoutsInRangeApiWorkoutsRangeGet>>>
export type ListWorkoutsInRangeApiWorkoutsRangeGetQueryError = HTTPValidationError


export function useListWorkoutsInRangeApiWorkoutsRangeGet<TData = Awaited<ReturnType<typeof listWorkoutsInRangeApiWorkoutsRangeGet>>, TError = HTTPValidationError>(
 params: ListWorkoutsInRangeApiWorkoutsRangeGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWorkoutsInRangeApiWorkoutsRangeGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listWorkoutsInRangeApiWorkoutsRangeGet>>,
          TError,
          Awaited<ReturnType<typeof listWorkoutsInRangeApiWorkoutsRangeGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListWorkoutsInRangeApiWorkoutsRangeGet<TData = Awaited<ReturnType<typeof listWorkoutsInRangeApiWorkoutsRangeGet>>, TError = HTTPValidationError>(
 params: ListWorkoutsInRangeApiWorkoutsRangeGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWorkoutsInRangeApiWorkoutsRangeGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listWorkoutsInRangeApiWorkoutsRangeGet>>,
          TError,
          Awaited<ReturnType<typeof listWorkoutsInRangeApiWorkoutsRangeGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListWorkoutsInRangeApiWorkoutsRangeGet<TData = Awaited<ReturnType<typeof listWorkoutsInRangeApiWorkoutsRangeGet>>, TError = HTTPValidationError>(
 params: ListWorkoutsInRangeApiWorkoutsRangeGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWorkoutsInRangeApiWorkoutsRangeGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Workouts In Range
 */

export function useListWorkoutsInRangeApiWorkoutsRangeGet<TData = Awaited<ReturnType<typeof listWorkoutsInRangeApiWorkoutsRangeGet>>, TError = HTTPValidationError>(
 params: ListWorkoutsInRangeApiWorkoutsRangeGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listWorkoutsInRangeApiWorkoutsRangeGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListWorkoutsInRangeApiWorkoutsRangeGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Calendar
 */
export const getCalendarApiWorkoutsCalendarGet = (
    params: GetCalendarApiWorkoutsCalendarGetParams,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<unknown>(
      {url: `/api/workouts/calendar`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetCalendarApiWorkoutsCalendarGetQueryKey = (params?: GetCalendarApiWorkoutsCalendarGetParams,) => {
    return [
    `/api/workouts/calendar`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetCalendarApiWorkoutsCalendarGetQueryOptions = <TData = Awaited<ReturnType<typeof getCalendarApiWorkoutsCalendarGet>>, TError = HTTPValidationError>(params: GetCalendarApiWorkoutsCalendarGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalendarApiWorkoutsCalendarGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCalendarApiWorkoutsCalendarGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCalendarApiWorkoutsCalendarGet>>> = ({ signal }) => getCalendarApiWorkoutsCalendarGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCalendarApiWorkoutsCalendarGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCalendarApiWorkoutsCalendarGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCalendarApiWorkoutsCalendarGet>>>
export type GetCalendarApiWorkoutsCalendarGetQueryError = HTTPValidationError


export function useGetCalendarApiWorkoutsCalendarGet<TData = Awaited<ReturnType<typeof getCalendarApiWorkoutsCalendarGet>>, TError = HTTPValidationError>(
 params: GetCalendarApiWorkoutsCalendarGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalendarApiWorkoutsCalendarGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCalendarApiWorkoutsCalendarGet>>,
          TError,
          Awaited<ReturnType<typeof getCalendarApiWorkoutsCalendarGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCalendarApiWorkoutsCalendarGet<TData = Awaited<ReturnType<typeof getCalendarApiWorkoutsCalendarGet>>, TError = HTTPValidationError>(
 params: GetCalendarApiWorkoutsCalendarGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalendarApiWorkoutsCalendarGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCalendarApiWorkoutsCalendarGet>>,
          TError,
          Awaited<ReturnType<typeof getCalendarApiWorkoutsCalendarGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCalendarApiWorkoutsCalendarGet<TData = Awaited<ReturnType<typeof getCalendarApiWorkoutsCalendarGet>>, TError = HTTPValidationError>(
 params: GetCalendarApiWorkoutsCalendarGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalendarApiWorkoutsCalendarGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Calendar
 */

export function useGetCalendarApiWorkoutsCalendarGet<TData = Awaited<ReturnType<typeof getCalendarApiWorkoutsCalendarGet>>, TError = HTTPValidationError>(
 params: GetCalendarApiWorkoutsCalendarGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCalendarApiWorkoutsCalendarGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCalendarApiWorkoutsCalendarGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get Workout Detail
 */
export const getWorkoutDetailApiWorkoutsWorkoutIdGet = (
    workoutId: number,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<unknown>(
      {url: `/api/workouts/${workoutId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetWorkoutDetailApiWorkoutsWorkoutIdGetQueryKey = (workoutId: number,) => {
    return [
    `/api/workouts/${workoutId}`
    ] as const;
    }

    
export const getGetWorkoutDetailApiWorkoutsWorkoutIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getWorkoutDetailApiWorkoutsWorkoutIdGet>>, TError = HTTPValidationError>(workoutId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkoutDetailApiWorkoutsWorkoutIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWorkoutDetailApiWorkoutsWorkoutIdGetQueryKey(workoutId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkoutDetailApiWorkoutsWorkoutIdGet>>> = ({ signal }) => getWorkoutDetailApiWorkoutsWorkoutIdGet(workoutId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(workoutId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWorkoutDetailApiWorkoutsWorkoutIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWorkoutDetailApiWorkoutsWorkoutIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkoutDetailApiWorkoutsWorkoutIdGet>>>
export type GetWorkoutDetailApiWorkoutsWorkoutIdGetQueryError = HTTPValidationError


export function useGetWorkoutDetailApiWorkoutsWorkoutIdGet<TData = Awaited<ReturnType<typeof getWorkoutDetailApiWorkoutsWorkoutIdGet>>, TError = HTTPValidationError>(
 workoutId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkoutDetailApiWorkoutsWorkoutIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkoutDetailApiWorkoutsWorkoutIdGet>>,
          TError,
          Awaited<ReturnType<typeof getWorkoutDetailApiWorkoutsWorkoutIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWorkoutDetailApiWorkoutsWorkoutIdGet<TData = Awaited<ReturnType<typeof getWorkoutDetailApiWorkoutsWorkoutIdGet>>, TError = HTTPValidationError>(
 workoutId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkoutDetailApiWorkoutsWorkoutIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkoutDetailApiWorkoutsWorkoutIdGet>>,
          TError,
          Awaited<ReturnType<typeof getWorkoutDetailApiWorkoutsWorkoutIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWorkoutDetailApiWorkoutsWorkoutIdGet<TData = Awaited<ReturnType<typeof getWorkoutDetailApiWorkoutsWorkoutIdGet>>, TError = HTTPValidationError>(
 workoutId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkoutDetailApiWorkoutsWorkoutIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Workout Detail
 */

export function useGetWorkoutDetailApiWorkoutsWorkoutIdGet<TData = Awaited<ReturnType<typeof getWorkoutDetailApiWorkoutsWorkoutIdGet>>, TError = HTTPValidationError>(
 workoutId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkoutDetailApiWorkoutsWorkoutIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWorkoutDetailApiWorkoutsWorkoutIdGetQueryOptions(workoutId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Delete Workout
 */
export const deleteWorkoutApiWorkoutsWorkoutIdDelete = (
    workoutId: number,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<void>(
      {url: `/api/workouts/${workoutId}`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeleteWorkoutApiWorkoutsWorkoutIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWorkoutApiWorkoutsWorkoutIdDelete>>, TError,{workoutId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteWorkoutApiWorkoutsWorkoutIdDelete>>, TError,{workoutId: number}, TContext> => {

const mutationKey = ['deleteWorkoutApiWorkoutsWorkoutIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteWorkoutApiWorkoutsWorkoutIdDelete>>, {workoutId: number}> = (props) => {
          const {workoutId} = props ?? {};

          return  deleteWorkoutApiWorkoutsWorkoutIdDelete(workoutId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteWorkoutApiWorkoutsWorkoutIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteWorkoutApiWorkoutsWorkoutIdDelete>>>
    
    export type DeleteWorkoutApiWorkoutsWorkoutIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Workout
 */
export const useDeleteWorkoutApiWorkoutsWorkoutIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWorkoutApiWorkoutsWorkoutIdDelete>>, TError,{workoutId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteWorkoutApiWorkoutsWorkoutIdDelete>>,
        TError,
        {workoutId: number},
        TContext
      > => {
      return useMutation(getDeleteWorkoutApiWorkoutsWorkoutIdDeleteMutationOptions(options), queryClient);
    }
    