/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gym Tracker API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ExerciseCreate,
  ExerciseUpdate,
  HTTPValidationError,
  ListExercisesApiExercisesGetParams
} from '../model';

import { customAxiosInstance } from '../../lib/axios-instance';




/**
 * @summary List Exercises
 */
export const listExercisesApiExercisesGet = (
    params?: ListExercisesApiExercisesGetParams,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<unknown>(
      {url: `/api/exercises`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListExercisesApiExercisesGetQueryKey = (params?: ListExercisesApiExercisesGetParams,) => {
    return [
    `/api/exercises`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListExercisesApiExercisesGetQueryOptions = <TData = Awaited<ReturnType<typeof listExercisesApiExercisesGet>>, TError = HTTPValidationError>(params?: ListExercisesApiExercisesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExercisesApiExercisesGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListExercisesApiExercisesGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listExercisesApiExercisesGet>>> = ({ signal }) => listExercisesApiExercisesGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listExercisesApiExercisesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListExercisesApiExercisesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listExercisesApiExercisesGet>>>
export type ListExercisesApiExercisesGetQueryError = HTTPValidationError


export function useListExercisesApiExercisesGet<TData = Awaited<ReturnType<typeof listExercisesApiExercisesGet>>, TError = HTTPValidationError>(
 params: undefined |  ListExercisesApiExercisesGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExercisesApiExercisesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listExercisesApiExercisesGet>>,
          TError,
          Awaited<ReturnType<typeof listExercisesApiExercisesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListExercisesApiExercisesGet<TData = Awaited<ReturnType<typeof listExercisesApiExercisesGet>>, TError = HTTPValidationError>(
 params?: ListExercisesApiExercisesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExercisesApiExercisesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listExercisesApiExercisesGet>>,
          TError,
          Awaited<ReturnType<typeof listExercisesApiExercisesGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListExercisesApiExercisesGet<TData = Awaited<ReturnType<typeof listExercisesApiExercisesGet>>, TError = HTTPValidationError>(
 params?: ListExercisesApiExercisesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExercisesApiExercisesGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Exercises
 */

export function useListExercisesApiExercisesGet<TData = Awaited<ReturnType<typeof listExercisesApiExercisesGet>>, TError = HTTPValidationError>(
 params?: ListExercisesApiExercisesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listExercisesApiExercisesGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListExercisesApiExercisesGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create Exercise
 */
export const createExerciseApiExercisesPost = (
    exerciseCreate: ExerciseCreate,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<unknown>(
      {url: `/api/exercises`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: exerciseCreate, signal
    },
      );
    }
  


export const getCreateExerciseApiExercisesPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createExerciseApiExercisesPost>>, TError,{data: ExerciseCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createExerciseApiExercisesPost>>, TError,{data: ExerciseCreate}, TContext> => {

const mutationKey = ['createExerciseApiExercisesPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createExerciseApiExercisesPost>>, {data: ExerciseCreate}> = (props) => {
          const {data} = props ?? {};

          return  createExerciseApiExercisesPost(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateExerciseApiExercisesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createExerciseApiExercisesPost>>>
    export type CreateExerciseApiExercisesPostMutationBody = ExerciseCreate
    export type CreateExerciseApiExercisesPostMutationError = HTTPValidationError

    /**
 * @summary Create Exercise
 */
export const useCreateExerciseApiExercisesPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createExerciseApiExercisesPost>>, TError,{data: ExerciseCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createExerciseApiExercisesPost>>,
        TError,
        {data: ExerciseCreate},
        TContext
      > => {
      return useMutation(getCreateExerciseApiExercisesPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Exercise
 */
export const getExerciseApiExercisesExerciseIdGet = (
    exerciseId: number,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<unknown>(
      {url: `/api/exercises/${exerciseId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetExerciseApiExercisesExerciseIdGetQueryKey = (exerciseId: number,) => {
    return [
    `/api/exercises/${exerciseId}`
    ] as const;
    }

    
export const getGetExerciseApiExercisesExerciseIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getExerciseApiExercisesExerciseIdGet>>, TError = HTTPValidationError>(exerciseId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExerciseApiExercisesExerciseIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetExerciseApiExercisesExerciseIdGetQueryKey(exerciseId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getExerciseApiExercisesExerciseIdGet>>> = ({ signal }) => getExerciseApiExercisesExerciseIdGet(exerciseId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(exerciseId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getExerciseApiExercisesExerciseIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetExerciseApiExercisesExerciseIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getExerciseApiExercisesExerciseIdGet>>>
export type GetExerciseApiExercisesExerciseIdGetQueryError = HTTPValidationError


export function useGetExerciseApiExercisesExerciseIdGet<TData = Awaited<ReturnType<typeof getExerciseApiExercisesExerciseIdGet>>, TError = HTTPValidationError>(
 exerciseId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExerciseApiExercisesExerciseIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExerciseApiExercisesExerciseIdGet>>,
          TError,
          Awaited<ReturnType<typeof getExerciseApiExercisesExerciseIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExerciseApiExercisesExerciseIdGet<TData = Awaited<ReturnType<typeof getExerciseApiExercisesExerciseIdGet>>, TError = HTTPValidationError>(
 exerciseId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExerciseApiExercisesExerciseIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExerciseApiExercisesExerciseIdGet>>,
          TError,
          Awaited<ReturnType<typeof getExerciseApiExercisesExerciseIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExerciseApiExercisesExerciseIdGet<TData = Awaited<ReturnType<typeof getExerciseApiExercisesExerciseIdGet>>, TError = HTTPValidationError>(
 exerciseId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExerciseApiExercisesExerciseIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Exercise
 */

export function useGetExerciseApiExercisesExerciseIdGet<TData = Awaited<ReturnType<typeof getExerciseApiExercisesExerciseIdGet>>, TError = HTTPValidationError>(
 exerciseId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExerciseApiExercisesExerciseIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetExerciseApiExercisesExerciseIdGetQueryOptions(exerciseId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update Exercise
 */
export const updateExerciseApiExercisesExerciseIdPatch = (
    exerciseId: number,
    exerciseUpdate: ExerciseUpdate,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<unknown>(
      {url: `/api/exercises/${exerciseId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: exerciseUpdate, signal
    },
      );
    }
  


export const getUpdateExerciseApiExercisesExerciseIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateExerciseApiExercisesExerciseIdPatch>>, TError,{exerciseId: number;data: ExerciseUpdate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateExerciseApiExercisesExerciseIdPatch>>, TError,{exerciseId: number;data: ExerciseUpdate}, TContext> => {

const mutationKey = ['updateExerciseApiExercisesExerciseIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateExerciseApiExercisesExerciseIdPatch>>, {exerciseId: number;data: ExerciseUpdate}> = (props) => {
          const {exerciseId,data} = props ?? {};

          return  updateExerciseApiExercisesExerciseIdPatch(exerciseId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateExerciseApiExercisesExerciseIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateExerciseApiExercisesExerciseIdPatch>>>
    export type UpdateExerciseApiExercisesExerciseIdPatchMutationBody = ExerciseUpdate
    export type UpdateExerciseApiExercisesExerciseIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Exercise
 */
export const useUpdateExerciseApiExercisesExerciseIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateExerciseApiExercisesExerciseIdPatch>>, TError,{exerciseId: number;data: ExerciseUpdate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateExerciseApiExercisesExerciseIdPatch>>,
        TError,
        {exerciseId: number;data: ExerciseUpdate},
        TContext
      > => {
      return useMutation(getUpdateExerciseApiExercisesExerciseIdPatchMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete Exercise
 */
export const deleteExerciseApiExercisesExerciseIdDelete = (
    exerciseId: number,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<void>(
      {url: `/api/exercises/${exerciseId}`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeleteExerciseApiExercisesExerciseIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteExerciseApiExercisesExerciseIdDelete>>, TError,{exerciseId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteExerciseApiExercisesExerciseIdDelete>>, TError,{exerciseId: number}, TContext> => {

const mutationKey = ['deleteExerciseApiExercisesExerciseIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteExerciseApiExercisesExerciseIdDelete>>, {exerciseId: number}> = (props) => {
          const {exerciseId} = props ?? {};

          return  deleteExerciseApiExercisesExerciseIdDelete(exerciseId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteExerciseApiExercisesExerciseIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteExerciseApiExercisesExerciseIdDelete>>>
    
    export type DeleteExerciseApiExercisesExerciseIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Exercise
 */
export const useDeleteExerciseApiExercisesExerciseIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteExerciseApiExercisesExerciseIdDelete>>, TError,{exerciseId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteExerciseApiExercisesExerciseIdDelete>>,
        TError,
        {exerciseId: number},
        TContext
      > => {
      return useMutation(getDeleteExerciseApiExercisesExerciseIdDeleteMutationOptions(options), queryClient);
    }
    