/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gym Tracker API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  LoginRequest,
  LoginResponse
} from '../model';

import { customAxiosInstance } from '../../lib/axios-instance';




/**
 * Exchange username/password for a JWT (used by the React frontend).
 * @summary Api Login
 */
export const apiLoginApiAuthLoginPost = (
    loginRequest: LoginRequest,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<LoginResponse>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest, signal
    },
      );
    }
  


export const getApiLoginApiAuthLoginPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiLoginApiAuthLoginPost>>, TError,{data: LoginRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof apiLoginApiAuthLoginPost>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['apiLoginApiAuthLoginPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof apiLoginApiAuthLoginPost>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  apiLoginApiAuthLoginPost(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ApiLoginApiAuthLoginPostMutationResult = NonNullable<Awaited<ReturnType<typeof apiLoginApiAuthLoginPost>>>
    export type ApiLoginApiAuthLoginPostMutationBody = LoginRequest
    export type ApiLoginApiAuthLoginPostMutationError = HTTPValidationError

    /**
 * @summary Api Login
 */
export const useApiLoginApiAuthLoginPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof apiLoginApiAuthLoginPost>>, TError,{data: LoginRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof apiLoginApiAuthLoginPost>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {
      return useMutation(getApiLoginApiAuthLoginPostMutationOptions(options), queryClient);
    }
    