/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gym Tracker API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  SetCreate,
  SetUpdate
} from '../model';

import { customAxiosInstance } from '../../lib/axios-instance';




/**
 * @summary Log Set
 */
export const logSetApiSetsPost = (
    setCreate: SetCreate,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<unknown>(
      {url: `/api/sets`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: setCreate, signal
    },
      );
    }
  


export const getLogSetApiSetsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logSetApiSetsPost>>, TError,{data: SetCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof logSetApiSetsPost>>, TError,{data: SetCreate}, TContext> => {

const mutationKey = ['logSetApiSetsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logSetApiSetsPost>>, {data: SetCreate}> = (props) => {
          const {data} = props ?? {};

          return  logSetApiSetsPost(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LogSetApiSetsPostMutationResult = NonNullable<Awaited<ReturnType<typeof logSetApiSetsPost>>>
    export type LogSetApiSetsPostMutationBody = SetCreate
    export type LogSetApiSetsPostMutationError = HTTPValidationError

    /**
 * @summary Log Set
 */
export const useLogSetApiSetsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logSetApiSetsPost>>, TError,{data: SetCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logSetApiSetsPost>>,
        TError,
        {data: SetCreate},
        TContext
      > => {
      return useMutation(getLogSetApiSetsPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Update Set
 */
export const updateSetApiSetsSetIdPatch = (
    setId: number,
    setUpdate: SetUpdate,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<unknown>(
      {url: `/api/sets/${setId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: setUpdate, signal
    },
      );
    }
  


export const getUpdateSetApiSetsSetIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSetApiSetsSetIdPatch>>, TError,{setId: number;data: SetUpdate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateSetApiSetsSetIdPatch>>, TError,{setId: number;data: SetUpdate}, TContext> => {

const mutationKey = ['updateSetApiSetsSetIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSetApiSetsSetIdPatch>>, {setId: number;data: SetUpdate}> = (props) => {
          const {setId,data} = props ?? {};

          return  updateSetApiSetsSetIdPatch(setId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateSetApiSetsSetIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateSetApiSetsSetIdPatch>>>
    export type UpdateSetApiSetsSetIdPatchMutationBody = SetUpdate
    export type UpdateSetApiSetsSetIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Set
 */
export const useUpdateSetApiSetsSetIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSetApiSetsSetIdPatch>>, TError,{setId: number;data: SetUpdate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSetApiSetsSetIdPatch>>,
        TError,
        {setId: number;data: SetUpdate},
        TContext
      > => {
      return useMutation(getUpdateSetApiSetsSetIdPatchMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete Set
 */
export const deleteSetApiSetsSetIdDelete = (
    setId: number,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<void>(
      {url: `/api/sets/${setId}`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeleteSetApiSetsSetIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSetApiSetsSetIdDelete>>, TError,{setId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteSetApiSetsSetIdDelete>>, TError,{setId: number}, TContext> => {

const mutationKey = ['deleteSetApiSetsSetIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSetApiSetsSetIdDelete>>, {setId: number}> = (props) => {
          const {setId} = props ?? {};

          return  deleteSetApiSetsSetIdDelete(setId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteSetApiSetsSetIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSetApiSetsSetIdDelete>>>
    
    export type DeleteSetApiSetsSetIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Set
 */
export const useDeleteSetApiSetsSetIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSetApiSetsSetIdDelete>>, TError,{setId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteSetApiSetsSetIdDelete>>,
        TError,
        {setId: number},
        TContext
      > => {
      return useMutation(getDeleteSetApiSetsSetIdDeleteMutationOptions(options), queryClient);
    }
    