/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gym Tracker API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  MuscleGroupCreate,
  MuscleGroupUpdate
} from '../model';

import { customAxiosInstance } from '../../lib/axios-instance';




/**
 * @summary List Muscle Groups
 */
export const listMuscleGroupsApiMuscleGroupsGet = (
    
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<unknown>(
      {url: `/api/muscle-groups`, method: 'GET', signal
    },
      );
    }
  



export const getListMuscleGroupsApiMuscleGroupsGetQueryKey = () => {
    return [
    `/api/muscle-groups`
    ] as const;
    }

    
export const getListMuscleGroupsApiMuscleGroupsGetQueryOptions = <TData = Awaited<ReturnType<typeof listMuscleGroupsApiMuscleGroupsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMuscleGroupsApiMuscleGroupsGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMuscleGroupsApiMuscleGroupsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMuscleGroupsApiMuscleGroupsGet>>> = ({ signal }) => listMuscleGroupsApiMuscleGroupsGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMuscleGroupsApiMuscleGroupsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMuscleGroupsApiMuscleGroupsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listMuscleGroupsApiMuscleGroupsGet>>>
export type ListMuscleGroupsApiMuscleGroupsGetQueryError = unknown


export function useListMuscleGroupsApiMuscleGroupsGet<TData = Awaited<ReturnType<typeof listMuscleGroupsApiMuscleGroupsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMuscleGroupsApiMuscleGroupsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMuscleGroupsApiMuscleGroupsGet>>,
          TError,
          Awaited<ReturnType<typeof listMuscleGroupsApiMuscleGroupsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMuscleGroupsApiMuscleGroupsGet<TData = Awaited<ReturnType<typeof listMuscleGroupsApiMuscleGroupsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMuscleGroupsApiMuscleGroupsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMuscleGroupsApiMuscleGroupsGet>>,
          TError,
          Awaited<ReturnType<typeof listMuscleGroupsApiMuscleGroupsGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMuscleGroupsApiMuscleGroupsGet<TData = Awaited<ReturnType<typeof listMuscleGroupsApiMuscleGroupsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMuscleGroupsApiMuscleGroupsGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Muscle Groups
 */

export function useListMuscleGroupsApiMuscleGroupsGet<TData = Awaited<ReturnType<typeof listMuscleGroupsApiMuscleGroupsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMuscleGroupsApiMuscleGroupsGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMuscleGroupsApiMuscleGroupsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create Muscle Group
 */
export const createMuscleGroupApiMuscleGroupsPost = (
    muscleGroupCreate: MuscleGroupCreate,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<unknown>(
      {url: `/api/muscle-groups`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: muscleGroupCreate, signal
    },
      );
    }
  


export const getCreateMuscleGroupApiMuscleGroupsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMuscleGroupApiMuscleGroupsPost>>, TError,{data: MuscleGroupCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createMuscleGroupApiMuscleGroupsPost>>, TError,{data: MuscleGroupCreate}, TContext> => {

const mutationKey = ['createMuscleGroupApiMuscleGroupsPost'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMuscleGroupApiMuscleGroupsPost>>, {data: MuscleGroupCreate}> = (props) => {
          const {data} = props ?? {};

          return  createMuscleGroupApiMuscleGroupsPost(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateMuscleGroupApiMuscleGroupsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createMuscleGroupApiMuscleGroupsPost>>>
    export type CreateMuscleGroupApiMuscleGroupsPostMutationBody = MuscleGroupCreate
    export type CreateMuscleGroupApiMuscleGroupsPostMutationError = HTTPValidationError

    /**
 * @summary Create Muscle Group
 */
export const useCreateMuscleGroupApiMuscleGroupsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMuscleGroupApiMuscleGroupsPost>>, TError,{data: MuscleGroupCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createMuscleGroupApiMuscleGroupsPost>>,
        TError,
        {data: MuscleGroupCreate},
        TContext
      > => {
      return useMutation(getCreateMuscleGroupApiMuscleGroupsPostMutationOptions(options), queryClient);
    }
    /**
 * @summary Get Muscle Group
 */
export const getMuscleGroupApiMuscleGroupsMuscleGroupIdGet = (
    muscleGroupId: number,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<unknown>(
      {url: `/api/muscle-groups/${muscleGroupId}`, method: 'GET', signal
    },
      );
    }
  



export const getGetMuscleGroupApiMuscleGroupsMuscleGroupIdGetQueryKey = (muscleGroupId: number,) => {
    return [
    `/api/muscle-groups/${muscleGroupId}`
    ] as const;
    }

    
export const getGetMuscleGroupApiMuscleGroupsMuscleGroupIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getMuscleGroupApiMuscleGroupsMuscleGroupIdGet>>, TError = HTTPValidationError>(muscleGroupId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMuscleGroupApiMuscleGroupsMuscleGroupIdGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMuscleGroupApiMuscleGroupsMuscleGroupIdGetQueryKey(muscleGroupId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMuscleGroupApiMuscleGroupsMuscleGroupIdGet>>> = ({ signal }) => getMuscleGroupApiMuscleGroupsMuscleGroupIdGet(muscleGroupId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(muscleGroupId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMuscleGroupApiMuscleGroupsMuscleGroupIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMuscleGroupApiMuscleGroupsMuscleGroupIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMuscleGroupApiMuscleGroupsMuscleGroupIdGet>>>
export type GetMuscleGroupApiMuscleGroupsMuscleGroupIdGetQueryError = HTTPValidationError


export function useGetMuscleGroupApiMuscleGroupsMuscleGroupIdGet<TData = Awaited<ReturnType<typeof getMuscleGroupApiMuscleGroupsMuscleGroupIdGet>>, TError = HTTPValidationError>(
 muscleGroupId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMuscleGroupApiMuscleGroupsMuscleGroupIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMuscleGroupApiMuscleGroupsMuscleGroupIdGet>>,
          TError,
          Awaited<ReturnType<typeof getMuscleGroupApiMuscleGroupsMuscleGroupIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMuscleGroupApiMuscleGroupsMuscleGroupIdGet<TData = Awaited<ReturnType<typeof getMuscleGroupApiMuscleGroupsMuscleGroupIdGet>>, TError = HTTPValidationError>(
 muscleGroupId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMuscleGroupApiMuscleGroupsMuscleGroupIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMuscleGroupApiMuscleGroupsMuscleGroupIdGet>>,
          TError,
          Awaited<ReturnType<typeof getMuscleGroupApiMuscleGroupsMuscleGroupIdGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMuscleGroupApiMuscleGroupsMuscleGroupIdGet<TData = Awaited<ReturnType<typeof getMuscleGroupApiMuscleGroupsMuscleGroupIdGet>>, TError = HTTPValidationError>(
 muscleGroupId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMuscleGroupApiMuscleGroupsMuscleGroupIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Muscle Group
 */

export function useGetMuscleGroupApiMuscleGroupsMuscleGroupIdGet<TData = Awaited<ReturnType<typeof getMuscleGroupApiMuscleGroupsMuscleGroupIdGet>>, TError = HTTPValidationError>(
 muscleGroupId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMuscleGroupApiMuscleGroupsMuscleGroupIdGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMuscleGroupApiMuscleGroupsMuscleGroupIdGetQueryOptions(muscleGroupId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update Muscle Group
 */
export const updateMuscleGroupApiMuscleGroupsMuscleGroupIdPatch = (
    muscleGroupId: number,
    muscleGroupUpdate: MuscleGroupUpdate,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<unknown>(
      {url: `/api/muscle-groups/${muscleGroupId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: muscleGroupUpdate, signal
    },
      );
    }
  


export const getUpdateMuscleGroupApiMuscleGroupsMuscleGroupIdPatchMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMuscleGroupApiMuscleGroupsMuscleGroupIdPatch>>, TError,{muscleGroupId: number;data: MuscleGroupUpdate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateMuscleGroupApiMuscleGroupsMuscleGroupIdPatch>>, TError,{muscleGroupId: number;data: MuscleGroupUpdate}, TContext> => {

const mutationKey = ['updateMuscleGroupApiMuscleGroupsMuscleGroupIdPatch'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMuscleGroupApiMuscleGroupsMuscleGroupIdPatch>>, {muscleGroupId: number;data: MuscleGroupUpdate}> = (props) => {
          const {muscleGroupId,data} = props ?? {};

          return  updateMuscleGroupApiMuscleGroupsMuscleGroupIdPatch(muscleGroupId,data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateMuscleGroupApiMuscleGroupsMuscleGroupIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateMuscleGroupApiMuscleGroupsMuscleGroupIdPatch>>>
    export type UpdateMuscleGroupApiMuscleGroupsMuscleGroupIdPatchMutationBody = MuscleGroupUpdate
    export type UpdateMuscleGroupApiMuscleGroupsMuscleGroupIdPatchMutationError = HTTPValidationError

    /**
 * @summary Update Muscle Group
 */
export const useUpdateMuscleGroupApiMuscleGroupsMuscleGroupIdPatch = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMuscleGroupApiMuscleGroupsMuscleGroupIdPatch>>, TError,{muscleGroupId: number;data: MuscleGroupUpdate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMuscleGroupApiMuscleGroupsMuscleGroupIdPatch>>,
        TError,
        {muscleGroupId: number;data: MuscleGroupUpdate},
        TContext
      > => {
      return useMutation(getUpdateMuscleGroupApiMuscleGroupsMuscleGroupIdPatchMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete Muscle Group
 */
export const deleteMuscleGroupApiMuscleGroupsMuscleGroupIdDelete = (
    muscleGroupId: number,
 signal?: AbortSignal
) => {
      
      
      return customAxiosInstance<void>(
      {url: `/api/muscle-groups/${muscleGroupId}`, method: 'DELETE', signal
    },
      );
    }
  


export const getDeleteMuscleGroupApiMuscleGroupsMuscleGroupIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMuscleGroupApiMuscleGroupsMuscleGroupIdDelete>>, TError,{muscleGroupId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteMuscleGroupApiMuscleGroupsMuscleGroupIdDelete>>, TError,{muscleGroupId: number}, TContext> => {

const mutationKey = ['deleteMuscleGroupApiMuscleGroupsMuscleGroupIdDelete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteMuscleGroupApiMuscleGroupsMuscleGroupIdDelete>>, {muscleGroupId: number}> = (props) => {
          const {muscleGroupId} = props ?? {};

          return  deleteMuscleGroupApiMuscleGroupsMuscleGroupIdDelete(muscleGroupId,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteMuscleGroupApiMuscleGroupsMuscleGroupIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMuscleGroupApiMuscleGroupsMuscleGroupIdDelete>>>
    
    export type DeleteMuscleGroupApiMuscleGroupsMuscleGroupIdDeleteMutationError = HTTPValidationError

    /**
 * @summary Delete Muscle Group
 */
export const useDeleteMuscleGroupApiMuscleGroupsMuscleGroupIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMuscleGroupApiMuscleGroupsMuscleGroupIdDelete>>, TError,{muscleGroupId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteMuscleGroupApiMuscleGroupsMuscleGroupIdDelete>>,
        TError,
        {muscleGroupId: number},
        TContext
      > => {
      return useMutation(getDeleteMuscleGroupApiMuscleGroupsMuscleGroupIdDeleteMutationOptions(options), queryClient);
    }
    