/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gym Tracker API
 * OpenAPI spec version: 1.0.0
 */

export type ListWorkoutsInRangeApiWorkoutsRangeGetParams = {
start_date: string;
end_date: string;
};
