/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gym Tracker API
 * OpenAPI spec version: 1.0.0
 */

export interface SetResponse {
  id: number;
  workout_exercise_id: number;
  rep_count?: number | null;
  weight?: number | null;
  duration_sec?: number | null;
}
