/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Gym Tracker API
 * OpenAPI spec version: 1.0.0
 */

export interface WorkoutExerciseCreate {
  workout_id: number;
  exercise_id: number;
}
